## `pymatgen.core.structure`

### `structure. `

In [2]:
from pymatgen.core import Structure

In [3]:
# Reading a cif file 
cif_file = "high_density_defects/MoS2_500/highMoS2cifs/MoS2_Mo56W4Se2S122_61d5e59e-335f-4026-bf18-15769c43a20b.cif"
structure = Structure.from_file(cif_file)

# print(structure)

/home/adamkim/anaconda3/envs/sample001/lib/python3.13/site-packages/pymatgen/core/structure.py:3087: EncodingWarning: We strongly encourage explicit `encoding`, and we would use UTF-8 by default as per PEP 686
  with zopen(filename, mode="rt", errors="replace") as file:
/home/adamkim/anaconda3/envs/sample001/lib/python3.13/site-packages/pymatgen/io/cif.py:1290: UserWarning: Issues encountered while parsing CIF: 47 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: " + "\n".join(self.warnings))


In [4]:
for i in structure:
    print(i)

[1.27612755e-05 1.84192230e+00 3.71975100e+00] Mo
[-1.59514511  4.6048168   3.719751  ] Mo
[-3.19030724  7.36771867  3.719751  ] Mo
[-4.78546086 10.1306058   3.719751  ] Mo
[-6.38061874 12.8935003   3.719751  ] Mo
[-7.97577661 15.6563948   3.719751  ] Mo
[-9.57093449 18.4192893   3.719751  ] Mo
[-11.16609236  21.1821838    3.719751  ] Mo
[8.50755882e-06 7.36771867e+00 3.71975100e+00] Mo
[-1.59514511 10.1306058   3.719751  ] Mo
[-4.78546086 15.6563948   3.719751  ] Mo
[-6.38061874 18.4192893   3.719751  ] Mo
[-7.97577661 21.1821838   3.719751  ] Mo
[6.38064426 1.8419223  3.719751  ] Mo
[4.78548639 4.6048168  3.719751  ] Mo
[3.19032426 7.36771867 3.719751  ] Mo
[ 1.59517064 10.1306058   3.719751  ] Mo
[1.27613508e-05 1.28935003e+01 3.71975100e+00] Mo
[-1.59514511 15.6563948   3.719751  ] Mo
[-4.78546086 21.1821838   3.719751  ] Mo
[9.57096001 1.8419223  3.719751  ] Mo
[7.97580214 4.6048168  3.719751  ] Mo
[6.38064001 7.36771867 3.719751  ] Mo
[ 3.19032851 12.8935003   3.719751  ] Mo
[ 1.

In [5]:
# Get number of sites
print(structure.num_sites )

184


In [ ]:
# Get types of species
print(structure.types_of_specie)

In [ ]:
# Get number of species
print(len(structure.types_of_specie))

In [ ]:
# Get atomic number of the type of specie
print(f"{i}:{i.Z for i in structure.types_of_specie})


In [6]:
# Get the chemical formula indicating total sites per element 
print(structure.formula)

Mo56 W4 Se2 S122


In [7]:
# Get reduced chemical formula
print(structure.reduced_formula)

Mo28W2SeS61


In [8]:
# Get all the species in the structure
print(structure.species)

[Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element Mo, Element W, Element W, Element W, Element W, Element Se, Element Se, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Element S, Elemen

In [9]:
# Extract the cartesian coordinates of every site
print(structure.cart_coords)

[[ 1.27612755e-05  1.84192230e+00  3.71975100e+00]
 [-1.59514511e+00  4.60481680e+00  3.71975100e+00]
 [-3.19030724e+00  7.36771867e+00  3.71975100e+00]
 [-4.78546086e+00  1.01306058e+01  3.71975100e+00]
 [-6.38061874e+00  1.28935003e+01  3.71975100e+00]
 [-7.97577661e+00  1.56563948e+01  3.71975100e+00]
 [-9.57093449e+00  1.84192893e+01  3.71975100e+00]
 [-1.11660924e+01  2.11821838e+01  3.71975100e+00]
 [ 8.50755882e-06  7.36771867e+00  3.71975100e+00]
 [-1.59514511e+00  1.01306058e+01  3.71975100e+00]
 [-4.78546086e+00  1.56563948e+01  3.71975100e+00]
 [-6.38061874e+00  1.84192893e+01  3.71975100e+00]
 [-7.97577661e+00  2.11821838e+01  3.71975100e+00]
 [ 6.38064426e+00  1.84192230e+00  3.71975100e+00]
 [ 4.78548639e+00  4.60481680e+00  3.71975100e+00]
 [ 3.19032426e+00  7.36771867e+00  3.71975100e+00]
 [ 1.59517064e+00  1.01306058e+01  3.71975100e+00]
 [ 1.27613508e-05  1.28935003e+01  3.71975100e+00]
 [-1.59514511e+00  1.56563948e+01  3.71975100e+00]
 [-4.78546086e+00  2.11821838e+

In [10]:
# Get fractional coordinates of every site
print(structure.frac_coords)

[[0.041667   0.083333   0.18598755]
 [0.041667   0.208333   0.18598755]
 [0.041667   0.33333333 0.18598755]
 [0.041667   0.458333   0.18598755]
 [0.041667   0.583333   0.18598755]
 [0.041667   0.708333   0.18598755]
 [0.041667   0.833333   0.18598755]
 [0.041667   0.958333   0.18598755]
 [0.166667   0.33333333 0.18598755]
 [0.166667   0.458333   0.18598755]
 [0.166667   0.708333   0.18598755]
 [0.166667   0.833333   0.18598755]
 [0.166667   0.958333   0.18598755]
 [0.291667   0.083333   0.18598755]
 [0.291667   0.208333   0.18598755]
 [0.291667   0.33333333 0.18598755]
 [0.291667   0.458333   0.18598755]
 [0.291667   0.583333   0.18598755]
 [0.291667   0.708333   0.18598755]
 [0.291667   0.958333   0.18598755]
 [0.416667   0.083333   0.18598755]
 [0.416667   0.208333   0.18598755]
 [0.416667   0.33333333 0.18598755]
 [0.416667   0.583333   0.18598755]
 [0.416667   0.708333   0.18598755]
 [0.416667   0.833333   0.18598755]
 [0.541667   0.083333   0.18598755]
 [0.541667   0.208333   0.18

In [11]:
# Get the atomic numbers of the sepcies in the structure
print(structure.atomic_numbers) # This produces a tuple

# To change from tuple to  list, you can use list()

sample = list(structure.atomic_numbers)
print(sample)

(42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 74, 74, 74, 74, 34, 34, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16)
[42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 74, 74, 74, 74, 34, 34, 16, 16, 16, 16

In [12]:
# Get the combined element type, fractional and cartecian coordinates
print(structure.sites)

[PeriodicSite: Mo0 (Mo) (1.276e-05, 1.842, 3.72) [0.04167, 0.08333, 0.186], PeriodicSite: Mo1 (Mo) (-1.595, 4.605, 3.72) [0.04167, 0.2083, 0.186], PeriodicSite: Mo2 (Mo) (-3.19, 7.368, 3.72) [0.04167, 0.3333, 0.186], PeriodicSite: Mo3 (Mo) (-4.785, 10.13, 3.72) [0.04167, 0.4583, 0.186], PeriodicSite: Mo4 (Mo) (-6.381, 12.89, 3.72) [0.04167, 0.5833, 0.186], PeriodicSite: Mo5 (Mo) (-7.976, 15.66, 3.72) [0.04167, 0.7083, 0.186], PeriodicSite: Mo6 (Mo) (-9.571, 18.42, 3.72) [0.04167, 0.8333, 0.186], PeriodicSite: Mo7 (Mo) (-11.17, 21.18, 3.72) [0.04167, 0.9583, 0.186], PeriodicSite: Mo8 (Mo) (8.508e-06, 7.368, 3.72) [0.1667, 0.3333, 0.186], PeriodicSite: Mo9 (Mo) (-1.595, 10.13, 3.72) [0.1667, 0.4583, 0.186], PeriodicSite: Mo10 (Mo) (-4.785, 15.66, 3.72) [0.1667, 0.7083, 0.186], PeriodicSite: Mo11 (Mo) (-6.381, 18.42, 3.72) [0.1667, 0.8333, 0.186], PeriodicSite: Mo12 (Mo) (-7.976, 21.18, 3.72) [0.1667, 0.9583, 0.186], PeriodicSite: Mo13 (Mo) (6.381, 1.842, 3.72) [0.2917, 0.08333, 0.186], P

In [ ]:
# What can you do with a site
for i in structure.sites[0]:
    print(i.specie) # the element involved
    print(i.specie.Z) # The atomic number of element involved
    print(i.frac_coords) # Can get the fractional coords


In [13]:
# Get the occupancy value of each specie
print(structure.species_and_occu)

[Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'), Composition('Mo1'),

In [14]:
for x in structure:
    print(f"{x.specie}:{x.frac_coords}")


Mo:[0.041667   0.083333   0.18598755]
Mo:[0.041667   0.208333   0.18598755]
Mo:[0.041667   0.33333333 0.18598755]
Mo:[0.041667   0.458333   0.18598755]
Mo:[0.041667   0.583333   0.18598755]
Mo:[0.041667   0.708333   0.18598755]
Mo:[0.041667   0.833333   0.18598755]
Mo:[0.041667   0.958333   0.18598755]
Mo:[0.166667   0.33333333 0.18598755]
Mo:[0.166667   0.458333   0.18598755]
Mo:[0.166667   0.708333   0.18598755]
Mo:[0.166667   0.833333   0.18598755]
Mo:[0.166667   0.958333   0.18598755]
Mo:[0.291667   0.083333   0.18598755]
Mo:[0.291667   0.208333   0.18598755]
Mo:[0.291667   0.33333333 0.18598755]
Mo:[0.291667   0.458333   0.18598755]
Mo:[0.291667   0.583333   0.18598755]
Mo:[0.291667   0.708333   0.18598755]
Mo:[0.291667   0.958333   0.18598755]
Mo:[0.416667   0.083333   0.18598755]
Mo:[0.416667   0.208333   0.18598755]
Mo:[0.416667   0.33333333 0.18598755]
Mo:[0.416667   0.583333   0.18598755]
Mo:[0.416667   0.708333   0.18598755]
Mo:[0.416667   0.833333   0.18598755]
Mo:[0.541667

In [15]:
sam = structure.make_supercell
print(sam)

<bound method Structure.make_supercell of Structure Summary
Lattice
    abc : 25.522526 25.5225261 20.0
 angles : 90.0 90.0 119.99999987000001
 volume : 11282.567473997196
      A : np.float64(25.522526) np.float64(0.0) np.float64(1.562803988602755e-15)
      B : np.float64(-12.76126299984953) np.float64(22.103156000305763) np.float64(1.5628039947259891e-15)
      C : np.float64(0.0) np.float64(0.0) np.float64(20.0)
    pbc : True True True
PeriodicSite: Mo0 (Mo) (1.276e-05, 1.842, 3.72) [0.04167, 0.08333, 0.186]
PeriodicSite: Mo1 (Mo) (-1.595, 4.605, 3.72) [0.04167, 0.2083, 0.186]
PeriodicSite: Mo2 (Mo) (-3.19, 7.368, 3.72) [0.04167, 0.3333, 0.186]
PeriodicSite: Mo3 (Mo) (-4.785, 10.13, 3.72) [0.04167, 0.4583, 0.186]
PeriodicSite: Mo4 (Mo) (-6.381, 12.89, 3.72) [0.04167, 0.5833, 0.186]
PeriodicSite: Mo5 (Mo) (-7.976, 15.66, 3.72) [0.04167, 0.7083, 0.186]
PeriodicSite: Mo6 (Mo) (-9.571, 18.42, 3.72) [0.04167, 0.8333, 0.186]
PeriodicSite: Mo7 (Mo) (-11.17, 21.18, 3.72) [0.04167, 0.9583,

### `pymatgen.core.Structure.lattice`
This contains methods used to find the general information of the structure.

In [16]:
# Extract lattice vectors as list
lat = structure.lattice
print(lat)

# Turn this into a matrix
lat_matrix = structure.lattice.matrix
print(lat_matrix)

25.522526 0.000000 0.000000
-12.761263 22.103156 0.000000
0.000000 0.000000 20.000000
[[ 2.55225260e+01  0.00000000e+00  1.56280399e-15]
 [-1.27612630e+01  2.21031560e+01  1.56280399e-15]
 [ 0.00000000e+00  0.00000000e+00  2.00000000e+01]]


In [17]:
# Extract lattice abc
print(f"abc values: {structure.lattice.abc}")
print(f"a: {structure.lattice.a}")
print(f"b: {structure.lattice.b}")
print(f"c: {structure.lattice.c}")

abc values: (25.522526, 25.5225261, 20.0)
a: 25.522526
b: 25.5225261
c: 20.0


In [18]:
# Get volume of the unit cell
print(structure.lattice.volume)

11282.567473997196


In [19]:
print(structure.lattice.pbc)

(True, True, True)


In [20]:
# Get angles
print(f"Angles: {structure.lattice.angles}")
print(f"Alpha: {structure.lattice.alpha}")
print(f"Beta: {structure.lattice.beta}")
print(f"Gamma: {structure.lattice.gamma}")

Angles: (90.0, 90.0, 119.99999987000001)
Alpha: 90.0
Beta: 90.0
Gamma: 119.99999987000001


In [21]:
print(structure.lattice.get_cartesian_coords)

<bound method Lattice.get_cartesian_coords of Lattice
    abc : 25.522526 25.5225261 20.0
 angles : 90.0 90.0 119.99999987000001
 volume : 11282.567473997196
      A : np.float64(25.522526) np.float64(0.0) np.float64(1.562803988602755e-15)
      B : np.float64(-12.76126299984953) np.float64(22.103156000305763) np.float64(1.5628039947259891e-15)
      C : np.float64(0.0) np.float64(0.0) np.float64(20.0)
    pbc : True True True>


In [22]:
# Get space group information
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
spg = SpacegroupAnalyzer(structure)
space_group = spg.get_space_group_symbol()
print(space_group)

P1


### `pymatgen.core.Lattice`

In [ ]:
from pymatgen.core import Lattice

In [24]:
# Silicon cubic lattice
lattice = Lattice.cubic(5.431)  # in cubic lattice, a = b = c
species = ["Si", "Si"]
coords = [[0, 0, 0], [0.25, 0.25, 0.25]]  # Diamond structure # Find coordinates of a unit cell

# Create Silicon unit cell
si_unit_cell = Structure(lattice, species, coords)

print(si_unit_cell)


Full Formula (Si2)
Reduced Formula: Si
abc   :   5.431000   5.431000   5.431000
angles:  90.000000  90.000000  90.000000
pbc   :       True       True       True
Sites (2)
  #  SP       a     b     c
---  ----  ----  ----  ----
  0  Si    0     0     0
  1  Si    0.25  0.25  0.25


In [25]:
# Define supercell scaling (2x2x2 expansion)
# these are the vector coordinates
supercell = si_unit_cell.make_supercell([[2, 0, 0], [0, 2, 0], [0, 0, 2]])

print("\nSupercell:")
print(supercell)



Supercell:
Full Formula (Si16)
Reduced Formula: Si
abc   :  10.862000  10.862000  10.862000
angles:  90.000000  90.000000  90.000000
pbc   :       True       True       True
Sites (16)
  #  SP        a      b      c
---  ----  -----  -----  -----
  0  Si    0      0      0
  1  Si    0      0      0.5
  2  Si    0      0.5    0
  3  Si    0      0.5    0.5
  4  Si    0.5    0      0
  5  Si    0.5    0      0.5
  6  Si    0.5    0.5    0
  7  Si    0.5    0.5    0.5
  8  Si    0.125  0.125  0.125
  9  Si    0.125  0.125  0.625
 10  Si    0.125  0.625  0.125
 11  Si    0.125  0.625  0.625
 12  Si    0.625  0.125  0.125
 13  Si    0.625  0.125  0.625
 14  Si    0.625  0.625  0.125
 15  Si    0.625  0.625  0.625


## `pymatgen.analysis`

This is used to convert cif files into crystal graphs
A graph has **nodes** (which will be the atoms) and **edges** (which is the bonds between the atoms)

In [26]:
from pymatgen.analysis.graphs import StructureGraph
from pymatgen.analysis.local_env import MinimumDistanceNN, CrystalNN # For strategy selection


In [27]:

# Create a graph based on nearest neighbors
graph_1 = StructureGraph.with_local_env_strategy(structure, MinimumDistanceNN())
graph_1


/tmp/ipykernel_5477/3244279980.py:2: FutureWarning: with_local_env_strategy is deprecated, and will be removed on 2025-03-20
Use from_local_env_strategy in pymatgen.analysis.graphs instead.
Deprecated on 2024-03-29.
  graph_1 = StructureGraph.with_local_env_strategy(structure, MinimumDistanceNN())


Structure Graph
Structure: 
Structure Summary
Lattice
    abc : 25.522526 25.5225261 20.0
 angles : 90.0 90.0 119.99999987000001
 volume : 11282.567473997196
      A : np.float64(25.522526) np.float64(0.0) np.float64(1.562803988602755e-15)
      B : np.float64(-12.76126299984953) np.float64(22.103156000305763) np.float64(1.5628039947259891e-15)
      C : np.float64(0.0) np.float64(0.0) np.float64(20.0)
    pbc : True True True
PeriodicSite: Mo0 (Mo) (1.276e-05, 1.842, 3.72) [0.04167, 0.08333, 0.186]
PeriodicSite: Mo1 (Mo) (-1.595, 4.605, 3.72) [0.04167, 0.2083, 0.186]
PeriodicSite: Mo2 (Mo) (-3.19, 7.368, 3.72) [0.04167, 0.3333, 0.186]
PeriodicSite: Mo3 (Mo) (-4.785, 10.13, 3.72) [0.04167, 0.4583, 0.186]
PeriodicSite: Mo4 (Mo) (-6.381, 12.89, 3.72) [0.04167, 0.5833, 0.186]
PeriodicSite: Mo5 (Mo) (-7.976, 15.66, 3.72) [0.04167, 0.7083, 0.186]
PeriodicSite: Mo6 (Mo) (-9.571, 18.42, 3.72) [0.04167, 0.8333, 0.186]
PeriodicSite: Mo7 (Mo) (-11.17, 21.18, 3.72) [0.04167, 0.9583, 0.186]
Period

In [28]:
graph_2 = StructureGraph.with_local_env_strategy(structure, CrystalNN())
graph_2

/tmp/ipykernel_5477/1494261320.py:1: FutureWarning: with_local_env_strategy is deprecated, and will be removed on 2025-03-20
Use from_local_env_strategy in pymatgen.analysis.graphs instead.
Deprecated on 2024-03-29.
  graph_2 = StructureGraph.with_local_env_strategy(structure, CrystalNN())
/home/adamkim/anaconda3/envs/sample001/lib/python3.13/site-packages/pymatgen/analysis/local_env.py:4158: UserWarning: No oxidation states specified on sites! For better results, set the site oxidation states in the structure.
  warnings.warn(
/home/adamkim/anaconda3/envs/sample001/lib/python3.13/site-packages/pymatgen/analysis/local_env.py:3951: UserWarning: CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.
  warnings.warn(


Structure Graph
Structure: 
Structure Summary
Lattice
    abc : 25.522526 25.5225261 20.0
 angles : 90.0 90.0 119.99999987000001
 volume : 11282.567473997196
      A : np.float64(25.522526) np.float64(0.0) np.float64(1.562803988602755e-15)
      B : np.float64(-12.76126299984953) np.float64(22.103156000305763) np.float64(1.5628039947259891e-15)
      C : np.float64(0.0) np.float64(0.0) np.float64(20.0)
    pbc : True True True
PeriodicSite: Mo0 (Mo) (1.276e-05, 1.842, 3.72) [0.04167, 0.08333, 0.186]
PeriodicSite: Mo1 (Mo) (-1.595, 4.605, 3.72) [0.04167, 0.2083, 0.186]
PeriodicSite: Mo2 (Mo) (-3.19, 7.368, 3.72) [0.04167, 0.3333, 0.186]
PeriodicSite: Mo3 (Mo) (-4.785, 10.13, 3.72) [0.04167, 0.4583, 0.186]
PeriodicSite: Mo4 (Mo) (-6.381, 12.89, 3.72) [0.04167, 0.5833, 0.186]
PeriodicSite: Mo5 (Mo) (-7.976, 15.66, 3.72) [0.04167, 0.7083, 0.186]
PeriodicSite: Mo6 (Mo) (-9.571, 18.42, 3.72) [0.04167, 0.8333, 0.186]
PeriodicSite: Mo7 (Mo) (-11.17, 21.18, 3.72) [0.04167, 0.9583, 0.186]
Period

In [29]:
# Get coordination number(local environment)
cnn = CrystalNN()

coordination_numbers = [cnn.get_cn(structure,i) for i in range(len(structure))]
coordination_numbers

[6,
 6,
 6,
 6,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 6,
 6,
 6,
 5,
 4,
 5,
 6,
 6,
 6,
 6,
 6,
 2,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3]

In [30]:
# Get the nearest neighbors
nearest_neighbor = [cnn.get_nn(structure,i) for i in range (len(structure))]
nearest_neighbor

[[PeriodicNeighbor: S122 (S) (1.595, 0.921, 5.285) [0.08333, 0.04167, 0.2642],
  PeriodicNeighbor: S62 (S) (1.595, 0.921, 2.155) [0.08333, 0.04167, 0.1077],
  PeriodicNeighbor: S177 (S) (-1.595, 0.921, 5.285) [-0.04167, 0.04167, 0.2642],
  PeriodicNeighbor: S115 (S) (-1.595, 0.921, 2.155) [-0.04167, 0.04167, 0.1077],
  PeriodicNeighbor: S63 (S) (-1.276e-05, 3.684, 2.155) [0.08333, 0.1667, 0.1077],
  PeriodicNeighbor: S123 (S) (-1.276e-05, 3.684, 5.285) [0.08333, 0.1667, 0.2642]],
 [PeriodicNeighbor: S64 (S) (-1.595, 6.447, 2.155) [0.08333, 0.2917, 0.1077],
  PeriodicNeighbor: S124 (S) (-1.595, 6.447, 5.285) [0.08333, 0.2917, 0.2642],
  PeriodicNeighbor: S178 (S) (-3.19, 3.684, 5.285) [-0.04167, 0.1667, 0.2642],
  PeriodicNeighbor: S116 (S) (-3.19, 3.684, 2.155) [-0.04167, 0.1667, 0.1077],
  PeriodicNeighbor: S123 (S) (-1.276e-05, 3.684, 5.285) [0.08333, 0.1667, 0.2642],
  PeriodicNeighbor: S63 (S) (-1.276e-05, 3.684, 2.155) [0.08333, 0.1667, 0.1077]],
 [PeriodicNeighbor: S64 (S) (-1.59